# Site settings
title: Arts & Crafts in Software
email: 
description: > # this means to ignore newlines until "baseurl:"
  Personal blog on my musings about everything software.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://leojh.com" # the base hostname & protocol for your site
twitter_username: leojh
github_username:  leojh

# Build settings
markdown: kramdown
